export enum MeetingEvent {
  JOIN = 'meeting:join',
  LEAVE = 'meeting:leave',
  PARTICIPANT_JOINED = 'meeting:participant_joined',
  PARTICIPANT_LEFT = 'meeting:participant_left',
  PARTICIPANT_UPDATED = 'meeting:participant_updated',
  PARTICIPANT_REMOVED = 'meeting:participant_removed',
  HOST_TRANSFERRED = 'meeting:host_transferred',
  STATUS_UPDATED = 'meeting:status_updated',
  ENDED = 'meeting:ended',
  JOIN_REQUESTED = 'meeting:join_requested',
  JOIN_REQUEST_UPDATED = 'meeting:join_request_updated',
  MESSAGE_SENT = 'meeting:message_sent',
  MESSAGE_UPDATED = 'meeting:message_updated',
  MESSAGE_READ = 'meeting:message_read',
}
