ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_REMOVED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_ROLE_UPDATED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'HOST_TRANSFERRED';
