import { DEFAULT_SPACE_CHANNEL_NAMES } from './space.enums';

export const DefaultSpaceChannelNames: DEFAULT_SPACE_CHANNEL_NAMES[] = [
  DEFAULT_SPACE_CHANNEL_NAMES.GENERAL,
  DEFAULT_SPACE_CHANNEL_NAMES.ANNOUNCEMENT,
  DEFAULT_SPACE_CHANNEL_NAMES.JUST_FOR_FUN,
];
