version: '3.8'

services:
  livekit:
    image: livekit/livekit-server:v1.13.5
    container_name: wh_livekit
    command: --config /etc/livekit/livekit.yaml
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    ports:
      - "${LIVEKIT_PORT}:7880"
      - "${LIVEKIT_RTC_TCP_PORT}:7881"
      - "${LIVEKIT_RTC_UDP_PORT}:7882/udp"
    volumes:
      - ../livekit/config/livekit.yaml:/etc/livekit/livekit.yaml:ro
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - wh_network
    restart: on-failure

