DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'NotificationType'
  ) THEN
    CREATE TYPE "NotificationType" AS ENUM (
      'SPACE_INVITATION',
      'SPACE_INVITATION_ACCEPTED',
      'SPACE_INVITATION_DECLINED',
      'SPACE_DISBANDED',
      'SPACE_MEMBER_REMOVED',
      'SPACE_OWNERSHIP_TRANSFERRED',
      'CHANNEL_DISBANDED',
      'CHAT_GROUP_INVITATION',
      'CHAT_INVITATION_ACCEPTED',
      'CHAT_INVITATION_DECLINED',
      'PROJECT_INVITATION',
      'PROJECT_TASK_ASSIGNED',
      'PROJECT_TASK_UPDATED',
      'PROJECT_SPRINT_STARTED',
      'CALENDAR_REMINDER',
      'MEETING_INVITATION',
      'MEETING_INVITATION_STATUS',
      'MEETING_INVITATION_DECLINED',
      'MEETING_UPDATED',
      'MEETING_CANCELLED'
    );
  END IF;
END $$;

ALTER TABLE "notifications"
ALTER COLUMN "type" TYPE "NotificationType"
USING "type"::text::"NotificationType";
