export enum ChatEvent {
  JOIN_CONVERSATION = "join_conversation",
  LEAVE_CONVERSATION = "leave_conversation",
  SEND_MESSAGE = "send_message",
  NEW_MESSAGE = "new_message",
  GROUP_INVITATION = "group_invitation",
  INVITATION_ACCEPTED = "invitation_accepted",
  INVITATION_DECLINED = "invitation_declined",
  MEDIA_UPDATED = "media_updated",
  POLL_UPDATED = "poll_updated",
  VOTE_POLL = "vote_poll",
  ADD_POLL_OPTION = "add_poll_option",
  EDIT_POLL = "edit_poll",
  MESSAGE_MOVED = "message_moved",
  NOTE_UPDATED = "note_updated",
  REACTION_UPDATED = "reaction_updated",
  MESSAGE_READ = "message_read",
  REACT_MESSAGE = "react_message",
  READ_MESSAGE = "read_message",
}
