version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: wh_notification_service
    container_name: wh_notification_service
    ports:
      - "8084:8084"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: sh -c "npx prisma generate && npx prisma db push --accept-data-loss && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8084"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
