version: '3.8'

services:
  frontend-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: wh_web
    container_name: wh_web
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      kong:
        condition: service_started
    networks:
      - wh_network
    restart: on-failure
