import type {
  CalendarRecurrenceEndType,
  CalendarRecurrenceFrequency,
  CalendarRecurrenceWeekday,
} from "../types/calendar.types";

export const CALENDAR_FORM_LOCALE = "en-US";

export const CALENDAR_FORM_COPY = {
  add: "Add",
  addConference: "Add video conferencing",
  addDeadline: "Add deadline",
  addDescription: "Add description",
  addDescriptionAttachment: "Add description or an attachment",
  addFile: "Add file",
  addGuests: "Add guests",
  addLocation: "Add location",
  addTask: "Add task",
  addTitle: "Add title",
  allDay: "All day",
  attendees: "Attendees",
  attachedDocuments: (count: number) =>
    `${count} attached ${count === 1 ? "document" : "documents"}`,
  calendar: "Calendar",
  cancel: "Cancel",
  close: "Close",
  conferenceUnavailable: "Video conferencing will be connected in a later phase",
  createEvent: "Create event",
  customRecurrence: "Custom recurrence",
  deadline: "Deadline",
  delete: "Delete",
  requiredFields: "Please fill in the required fields",
  done: "Done",
  editEvent: "Edit event",
  end: "End",
  endDate: "End date",
  endRangeInvalid: "End time must be after start time",
  endRangeTooShort: "Event must be at least 15 minutes",
  event: "Event",
  eventSaveFailed: "Could not save event",
  eventSaved: "Event saved",
  fewerOptions: "Fewer options",
  location: "Location",
  moreOptions: "More options",
  myTasks: "My tasks",
  noResults: "No results",
  notifyBefore: (minutes: number) => `Notify ${minutes} minutes before`,
  recurrence: "Repeat",
  recurrenceCustom: "Custom...",
  recurrenceDaily: "Daily",
  recurrenceEnds: "Ends",
  recurrenceMonthlyOn: (day: number) => `Monthly on day ${day}`,
  recurrenceNone: "Does not repeat",
  recurrenceRepeatEvery: "Repeat every",
  recurrenceRepeatOn: "Repeat on",
  recurrenceWeekdays: "Every weekday",
  recurrenceWeeklyOn: (weekday: string) => `Weekly on ${weekday}`,
  recurrenceYearlyOn: (date: string) => `Yearly on ${date}`,
  reminders: "Reminders",
  save: "Save",
  saving: "Saving...",
  searchAttendees: "Search users by email",
  searching: "Searching...",
  start: "Start",
  startDate: "Start date",
  task: "Task",
  timeZone: "Time zone",
} as const;

export const CALENDAR_FORM_RECURRENCE_UNITS: Record<CalendarRecurrenceFrequency, string> = {
  DAILY: "day",
  WEEKLY: "week",
  MONTHLY: "month",
  YEARLY: "year",
};

export const CALENDAR_FORM_WEEKDAY_INITIALS: Record<CalendarRecurrenceWeekday, string> = {
  MO: "M",
  TU: "T",
  WE: "W",
  TH: "T",
  FR: "F",
  SA: "S",
  SU: "S",
};

export const CALENDAR_FORM_RECURRENCE_END_LABELS: Record<CalendarRecurrenceEndType, string> = {
  never: "Never",
  on: "On date",
  after: "After",
};
