version: '3.8'

services:
  communication-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workspace_hub_communication_service
    ports:
      - "8083:8083"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: sh -c "npx prisma generate && npx prisma db push && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8083"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
