ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'JOIN_REQUESTED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'JOIN_APPROVED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'JOIN_REJECTED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_REMOVED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_ROLE_UPDATED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'HOST_TRANSFERRED';
ALTER TYPE "MeetingEventType" ADD VALUE IF NOT EXISTS 'ACCESS_UPDATED';
